### ISSUE TITLE
Request to set up team

### ISSUE THREAD

**Issue by genevaneva** [National-COVID-Cohort-Collaborative/CS-Rural-Health#1]
@jerrodanzalone 
Quick request from : @wibeasley 
Can you create a team for this repo and invite all of the Rural Health group members?

**Comment by jerrodanzalone** [comment]
@genevamarshall Do you want just the steroid team members or everyone added? Not confident the majority know how GitHub works or have accounts.

**Comment by genevaneva** [comment]
I sort of created this on @wibeasley 's behalf, but I think he meant everybody who will be using the repo (or for now everybody who's currently on it). He's going to be talking about it at today's meeting.

**Comment by genevaneva** [comment]
@jerrodanzalone do you mind adding me to this repo so I can upload codesets?

**Comment by jerrodanzalone** [comment]
@genevamarshall Done. Let me know if anyone else needs to be added. Thanks!

**Comment by genevaneva** [comment]
Thank you!
