### ISSUE TITLE
asthma codeset based on cdc categories from ICD 10 codes.

### ISSUE THREAD

**Issue by genevaneva** [National-COVID-Cohort-Collaborative/CS-Rural-Health#7]
I assembled this in the Concept Set Browser based on the results of the query below, but it does not seem to show up in the codeset_member table yet. The json has the appropriate concept ids, so hopefully this will update eventually. 

```sql
SELECT
  dd.icd_code
  ,dd.icd_description
  ,dd.concept_id as condition_source_concept_id
  ,dd.vocabulary_id as condition_source_vocabulary_id
 
  ,cr.concept_id_2                                                                         as standard_concept_id
  ,c.concept_name
  ,c.vocabulary_id as condition_vocabulary_id
  ,case 
    when icd_code like 'J45.2%' then 'mild intermittent asthma'
    when icd_code like 'J45.3%' then  'mild persistent asthma'
    when icd_code like 'J45.4%' then 'moderate persistent asthma'
    when icd_code like 'J45.5%' then 'severe persistent asthma'
    else 'other'                                                                       
  end as cdc_asthma_category
FROM cdw_outpost.lexis.dim_dx dd
  left  join cdw_omop_1.v6.concept_relationship cr on dd.concept_id = cr.concept_id_1 and relationship_id = 'Maps to'
  left  join cdw_omop_1.v6.concept              c  on cr.concept_id_2 = c.concept_id 
WHERE icd_code like 'J45%'
ORDER BY cdc_asthma_category

```

**Comment by wibeasley** [comment]
produced by @genevamarshall in https://unite.nih.gov/workspace/vector/view/ri.vector.main.workbook.69dc0fbc-b028-4c9f-a633-abc957c5284a?branch=master

|**Characteristic**         |**N = 1661759** |
|:--------------------------|:---------------|
|asthma_category_cdc        |                |
|none                       |1491995 (90%)   |
|mild intermittent asthma   |48940 (2.9%)    |
|mild persistent asthma     |16376 (1.0%)    |
|moderate persistent asthma |27886 (1.7%)    |
|severe persistent asthma   |6924 (0.4%)     |
|asthma - other             |69638 (4.2%)    |
[1] "Asthma categories by age"


|**Characteristic**         |**0-18**, N = 206790 |**19-50**, N = 774719 |**51-75**, N = 548494 |**76+**, N = 130044 |**Unknown**, N = 1712 |
|:--------------------------|:--------------------|:---------------------|:---------------------|:-------------------|:---------------------|
|asthma_category_cdc        |                     |                      |                      |                    |                      |
|none                       |184036 (89%)         |697598 (90%)          |488991 (89%)          |119804 (92%)        |1566 (91%)            |
|mild intermittent asthma   |8021 (3.9%)          |23912 (3.1%)          |14877 (2.7%)          |2100 (1.6%)         |30 (1.8%)             |
|mild persistent asthma     |3736 (1.8%)          |6450 (0.8%)           |5327 (1.0%)           |843 (0.6%)          |20 (1.2%)             |
|moderate persistent asthma |3442 (1.7%)          |11873 (1.5%)          |10856 (2.0%)          |1683 (1.3%)         |32 (1.9%)             |
|severe persistent asthma   |855 (0.4%)           |2581 (0.3%)           |3004 (0.5%)           |482 (0.4%)          |2 (0.1%)              |
|asthma - other             |6700 (3.2%)          |32305 (4.2%)          |25439 (4.6%)          |5132 (3.9%)         |62 (3.6%)             |
[1] "Steroid use by asthma categories"


|**Characteristic**      |**none**, N = 1491995 |**mild intermittent asthma**, N = 48940 |**mild persistent asthma**, N = 16376 |**moderate persistent asthma**, N = 27886 |**severe persistent asthma**, N = 6924 |**asthma - other**, N = 69638 |
|:-----------------------|:---------------------|:---------------------------------------|:-------------------------------------|:-----------------------------------------|:--------------------------------------|:-----------------------------|
|hydrocortisone_oral     |1383 (<0.1%)          |72 (0.1%)                               |27 (0.2%)                             |64 (0.2%)                                 |28 (0.4%)                              |127 (0.2%)                    |
|hydrocortisone_systemic |3815 (0.3%)           |170 (0.3%)                              |65 (0.4%)                             |125 (0.4%)                                |51 (0.7%)                              |359 (0.5%)                    |
|nasal_spray             |17249 (1.2%)          |2119 (4.3%)                             |1355 (8.3%)                           |3533 (13%)                                |1251 (18%)                             |2950 (4.2%)                   |
